// <auto-generated />
using FoodStop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodStop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240106202443_BranchDataSeeding")]
    partial class BranchDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodStop.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Branch");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Location = "Covai",
                            Name = "SpiceFusion Kitchen",
                            Phone = 123456789L
                        },
                        new
                        {
                            Id = 5,
                            Location = "Dharmapuri",
                            Name = "SavoryBite Delights",
                            Phone = 123456789L
                        },
                        new
                        {
                            Id = 6,
                            Location = "Ambur",
                            Name = "CrispyCrust Cafe",
                            Phone = 123456789L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
